config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :categories
  resources :user

  devise_for :users
  get 'welcome/index'

  resources :nota
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root 'welcome#index'
  #root  'sessions#new'

  devise_scope :user do
    authenticated :user do
      root 'welcome#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end



   resources :user do
    member do
      get :following, :followers
    end
  end

  resources :relationships,       only: [:create, :destroy]


end

app/controllers/nota_controller.rb
class NotaController < ApplicationController
  before_action :set_notum, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /nota
  # GET /nota.json
  def index
    #@nota = Notum.all
    @nota= current_user.notum
  end

  # GET /nota/1
  # GET /nota/1.json
  def show
  end

  # GET /nota/new
  def new
    @notum = Notum.new
  #  @categories=Category.all
    @categories=current_user.Category
    @userShared=User.all

  end

  # GET /nota/1/edit
  def edit
    @userShared=User.all
  end

  # POST /nota
  # POST /nota.json
  def create
    @notum = current_user.notum.new(notum_params)
    @notum.categories=params[:categories]
    @notum.userShared=params[:userShared]
    @notum.aux_user = current_user.id

    respond_to do |format|
      if @notum.save
        format.html { redirect_to @notum, notice: 'Notum was successfully created.' }
        format.json { render :show, status: :created, location: @notum }
      else
        format.html { render :new }
        format.json { render json: @notum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nota/1
  # PATCH/PUT /nota/1.json
  def update
    @notum.categories=params[:categories]
    @notum.userShared=params[:userShared]
    respond_to do |format|
      if @notum.update(notum_params)
        format.html { redirect_to @notum, notice: 'Notum was successfully updated.' }
        format.json { render :show, status: :ok, location: @notum }
      else
        format.html { render :edit }
        format.json { render json: @notum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nota/1
  # DELETE /nota/1.json
  def destroy
    #@notum.destroy
      aux = NoteShared.find_by notum_id: @notum.id , user_id: current_user.id
      aux.destroy
    if NoteShared.exists?(:notum_id => @notum.id) == false
      aux1 = Notum.find_by(:id => @notum.id)
      aux1.destroy
    end

    respond_to do |format|
      format.html { redirect_to nota_url, notice: 'Notum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notum
      @notum = Notum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notum_params
      params.require(:notum).permit(:image, :title, :body, :categories, :userShared)
    end


end

app/helpers/nota_helper.rb
module NotaHelper
end

app/views/nota/_form.html.erb
<%= form_with(model: notum, local: true) do |form| %>
  <% if notum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notum.errors.count, "error") %> prohibited this notum from being saved:</h2>

      <ul>
      <% notum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form>
  <div class="form-group">
    <label>Title</label>
    <div class="field" type="text" class="form-control">
      <% form.label :title %>
      <%= form.text_field :title, id: :notum_title,class:'form-control',placeholder:'Write the title of your note' %>
    </div>
    <label>Image</label>
    <div class="field">

      <%= form.file_field :image %>
    </div>

  </div>


  <div class="form-group">
    <label>Content</label>
    <div class="field" type="text" class="form-control" >
      <% form.label :body %>

      <%= form.text_area :body, id: :notum_body,class:'form-control', rows:'3' %>
    </div>

  </div>

  <div class="form-group">
    <label>Categories</label>
    <div class="field" type="text" class="form-control" >
      <%@categories = current_user.Category.all%>
      <%if @categories != nil%>
          <% @categories.each do |category|  %>
            <div class="field">
             <%=check_box_tag "categories[]",category.id %><%=category.name%>
            </div>
          <%end%>
      <%end%>
    </div>

  </div>

  <div class="form-group">
    <label>User shared</label>
    <div class="field" type="text" class="form-control" >
      <%if @userShared != nil%>
          <% @userShared.each do |user|  %>
          <%if current_user.following?(user)  && user.following?(current_user) %>
          <div class="field">
           <%=check_box_tag "userShared[]",user.id %><%=user.email%>
          </div>
          <%end%>
          <%end%>
      <%end%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<%end%>

app/views/nota/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="icon" type="image/png" href="assets/img/favicon.ico">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>Notes</title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport'/>
    <meta name="viewport" content="width=device-width" />

    <!-- Bootstrap core CSS     -->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="assets/css/animate.min.css" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="assets/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="assets/css/demo.css" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="assets/css/pe-icon-7-stroke.css" rel="stylesheet" />
</head>
<body>

<div class="wrapper">
    <div class="sidebar" data-color="azure">

    <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->


      <div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    APP NOTES
                </a>
            </div>

            <ul class="nav">
              <li>
                    <a href="http://localhost:3000/nota">
                        <i class="pe-7s-note2"></i>
                        <p>Notes</p>
                    </a>
                </li>
                <li>
                  <%@user = current_user%>
                    <a href="http://localhost:3000/user/<%=@user.id%>">
                        <i class="pe-7s-user"></i>
                        <p>User Profile</p>

                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/categories">
                        <i class="pe-7s-news-paper"></i>
                        <p>Notes Collections</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user">
                        <i class="pe-7s-science"></i>
                        <p>Search Users</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user/<%=@user.id%>/following">
                        <i class="pe-7s-users"></i>
                        <p>Friends</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user/<%=@user.id%>/followers">
                        <i class="pe-7s-bell"></i>
                        <p>Requests</p>
                    </a>
                </li>
            </ul>
      </div>
    </div>
    <div class="main-panel">
    <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                    </button>
                    <a class="navbar-brand" href="#">Notes</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                      <%if current_user.admin == true%>
                        <li>
                            <a href="http://localhost:3000/admin">
                                  <p>Admin</p>
                              </a>
                          </li>
                        <%end%>

                        <li>
                        <li>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
                </li>
                        </li>
            <li class="separator hidden-lg hidden-md"></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">Your Notes:</h4>
                            </div>
                            <div class="content table-responsive table-full-width">
                                <table class="table table-hover table-striped">
                                        <thead>
                                          <tr>
                                            <th>Title</th>
                                            <th>Body</th>
                                            <th colspan="3"></th>
                                          </tr>
                                        </thead>
                                        <tbody>
                                          <% @nota.each do |notum| %>
                                            <tr>
                                              <td><%= notum.title %></td>
                                              <td><%= notum.body %></td>
                                              <td><%= link_to 'Show', notum %></td>
                                              <td><%= link_to 'Edit', edit_notum_path(notum) %></td>
                                              <td><%= link_to 'Destroy', notum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                            </tr>
                                          <% end %>
                                        </tbody>
                                </table>
                                <%= link_to 'New Notum', new_notum_path %>
                                <%= link_to 'Atras', welcome_index_url %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>

                    </ul>
                </nav>
            </div>
        </footer>
    </div>
</div>

</body>

    <!--   Core JS Files   -->
    <script src="assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
  <script src="assets/js/bootstrap.min.js" type="text/javascript"></script>

  <!--  Charts Plugin -->
  <script src="assets/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="assets/js/bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
  <script src="assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

  <!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
  <script src="assets/js/demo.js"></script>



</html>

app/views/nota/new.html.erb
 <%if user_signed_in?%>
	<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/png" href="../assets/img/favicon.ico">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Notes</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="../assets/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="../assets/css/animate.min.css" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="../assets/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="../assets/css/demo.css" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="../assets/css/pe-icon-7-stroke.css" rel="stylesheet" />
</head>
<body>

<div class="wrapper">
    <div class="sidebar" data-color="azure">

    <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->


    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    APP NOTES
                </a>
            </div>

            <ul class="nav">
            	<li>
                    <a href="http://localhost:3000/nota">
                        <i class="pe-7s-note2"></i>
                        <p>Notes</p>
                    </a>
                </li>
                <li>
                	<%@user = current_user%>
                    <a href="http://localhost:3000/user/<%=@user.id%>">
                        <i class="pe-7s-user"></i>
                        <p>User Profile</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/categories">
                        <i class="pe-7s-news-paper"></i>
                        <p>Notes Collections</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user">
                        <i class="pe-7s-science"></i>
                        <p>Search Users</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user/<%=@user.id%>/following">
                        <i class="pe-7s-users"></i>
                        <p>Friends</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user/<%=@user.id%>/followers">
                        <i class="pe-7s-bell"></i>
                        <p>Requests</p>
                    </a>
                </li>
            </ul>
    	</div>
    </div>
    <div class="main-panel">
		<nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>

                    </button>
                    <a class="navbar-brand" href="#">Notes</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                    	<%if current_user.admin == true%>
	                    	<li>
	                        	<a href="http://localhost:3000/admin">
	                                <p>Admin</p>
	                            </a>
	                        </li>
                        <%end%>
                        <li>
                                <li>
									<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
								</li>
                        </li>
						<li class="separator hidden-lg hidden-md"></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">Create a new Note</h4>
                            </div>
                            <div class="content table-responsive table-full-width">
                                <%= render 'form', notum: @notum %>
                                <%= link_to 'Back', nota_path %>
                                <table class="table table-hover table-striped">

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>

                    </ul>
                </nav>
            </div>
        </footer>
    </div>
</div>

</body>

    <!--   Core JS Files   -->
    <script src="../assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
	<script src="../assets/js/bootstrap.min.js" type="text/javascript"></script>

	<!--  Charts Plugin -->
	<script src="../assets/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="../assets/js/bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="../assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
	<script src="../assets/js/demo.js"></script>



</html>

<%end%>

app/views/nota/show.html.erb
<%if user_signed_in?%>
 <!doctype html>
<html lang="en">
<head>
 <meta charset="utf-8" />
 <link rel="icon" type="image/png" href="../../assets/img/favicon.ico">
 <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

 <title>Notes</title>

 <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
   <meta name="viewport" content="width=device-width" />


   <!-- Bootstrap core CSS     -->
   <link href="../../assets/css/bootstrap.min.css" rel="stylesheet" />

   <!-- Animation library for notifications   -->
   <link href="../../assets/css/animate.min.css" rel="stylesheet"/>

   <!--  Light Bootstrap Table core CSS    -->
   <link href="../../assets/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet"/>


   <!--  CSS for Demo Purpose, don't include it in your project     -->
   <link href="../../assets/css/demo.css" rel="stylesheet" />


   <!--     Fonts and icons     -->
   <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
   <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
   <link href="../../assets/css/pe-icon-7-stroke.css" rel="stylesheet" />
</head>
<body>

<div class="wrapper">
   <div class="sidebar" data-color="azure">

   <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->


     <div class="sidebar-wrapper">
           <div class="logo">
               <a href="#" class="simple-text">
                   APP NOTES
               </a>
           </div>

           <ul class="nav">
             <li>
                   <a href="http://localhost:3000/nota">
                       <i class="pe-7s-note2"></i>
                       <p>Notes</p>
                   </a>
               </li>
               <li>
                 <%@user = current_user%>
                   <a href="http://localhost:3000/user/<%=@user.id%>">
                       <i class="pe-7s-user"></i>
                       <p>User Profile</p>
                   </a>
               </li>
               <li>
                   <a href="http://localhost:3000/categories">
                       <i class="pe-7s-news-paper"></i>
                       <p>Notes Collections</p>
                   </a>
               </li>
               <li>
                   <a href="http://localhost:3000/user">
                       <i class="pe-7s-science"></i>
                       <p>Search Users</p>
                   </a>
               </li>
               <li>
                   <a href="http://localhost:3000/user/<%=@user.id%>/following">
                       <i class="pe-7s-users"></i>
                       <p>Friends</p>
                   </a>
               </li>
               <li>
                   <a href="http://localhost:3000/user/<%=@user.id%>/followers">
                       <i class="pe-7s-bell"></i>
                       <p>Requests</p>
                   </a>
               </li>
           </ul>
     </div>
   </div>
   <div class="main-panel">
   <nav class="navbar navbar-default navbar-fixed">
           <div class="container-fluid">
               <div class="navbar-header">
                   <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                       <span class="sr-only">Toggle navigation</span>
                   </button>
                   <a class="navbar-brand" href="#">Notes</a>
               </div>
               <div class="collapse navbar-collapse">
                   <ul class="nav navbar-nav navbar-right">
                     <%if current_user.admin == true%>
                       <li>
                           <a href="http://localhost:3000/admin">
                                 <p>Admin</p>
                             </a>
                         </li>
                       <%end%>
                       <li>
                               <li>
                 <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
               </li>
                       </li>
           <li class="separator hidden-lg hidden-md"></li>
                   </ul>
               </div>
           </div>
       </nav>
       <div class="content">
           <div class="container-fluid">
               <div class="row">
                   <div class="col-md-12">
                       <div class="card">
                           <div class="header">
                               <h4 class="title">Show Notum</h4>
                           </div>
                           <div class="panel panel-default">
                               <div class="panel-heading">
                                 <h3 class="panel-title"><%=@notum.title %></h3>
                               </div>
                               <div class="panel-body">
                               <%= @notum.body %>
                               </div>
                               <div class="panel-body">
                              <h3 class="panel-title">Image</h3>
                               </div>


                                 <%=image_tag(@notum.image.url(:medium)) %>
                             </div>

                                   <%= link_to 'Back', nota_path %>

                           </div>
                       </div>
                   </div>
               </div>
           </div>
       </div>

       <footer class="footer">
           <div class="container-fluid">
               <nav class="pull-left">
                   <ul>

                   </ul>
               </nav>
           </div>
       </footer>
   </div>
</div>

</body>

   <!--   Core JS Files   -->
   <script src="../../assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
 <script src="../../assets/js/bootstrap.min.js" type="text/javascript"></script>

 <!--  Charts Plugin -->
 <script src="../../assets/js/chartist.min.js"></script>

   <!--  Notifications Plugin    -->
   <script src="../../assets/js/bootstrap-notify.js"></script>

   <!--  Google Maps Plugin    -->
   <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

   <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
 <script src="../../assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

 <!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
 <script src="../../assets/js/demo.js"></script>



</html>

<%end%>