config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :categories
  resources :user

  devise_for :users
  get 'welcome/index'

  resources :nota
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root 'welcome#index'
  #root  'sessions#new'

  devise_scope :user do
    authenticated :user do
      root 'welcome#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end



   resources :user do
    member do
      get :following, :followers
    end
  end

  resources :relationships,       only: [:create, :destroy]


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #has_many :Notum, dependent: :destroy
  has_many :Category, dependent: :destroy
  has_many :NoteShared
  has_many :note_shareds
  has_many :notum, through: :note_shareds

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower


    # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    if other_user != nil
      active_relationships.find_by(followed_id: other_user.id).destroy
    end
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

    # Returns true if the current user is followers the other user.
  def followers?(other_user)
    followers.include?(other_user)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

	 before_action :authenticate_user!
	def index
		@users= User.all
	end

	def show
		@users = User.find(params[:id])
	end


	def destroy

		#usuarios=current_user.active_relationships.find_by (params[:id])
		#usuarios=current_user.active_relationships.find_by (params[:followed_id])
		usuarios = User.find(params[:id])
		usuarios.unfollow(current_user)
		current_user.unfollow(usuarios)


		respond_to do |format|
			format.html { redirect_to followers_user_url, notice: 'Se ha eliminado esa relación' }
			format.json { head :no_content }
		end
	end
 def following
    @title = "Friends"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'

  end

  def followers
    @title = "Requests"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @users.id %></div>
  <%= f.submit "Add Friend", class: "btn btn-primary" %>
<% end %>

app/views/user/_follow_form.html.erb
  <div id="follow_form">
  <% if current_user.following?(@users) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>

app/views/user/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @users.id),
             html: { method: :delete }) do |f| %>

  <%= f.submit "Delete Friend", class: "btn btn-primary" %>
<% end %>

app/views/user/index.html.erb
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<link rel="icon" type="image/png" href="../assets/img/favicon.ico">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

<title>Notes</title>

<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
  <meta name="viewport" content="width=device-width" />


  <!-- Bootstrap core CSS     -->
  <link href="../assets/css/bootstrap.min.css" rel="stylesheet" />

  <!-- Animation library for notifications   -->
  <link href="../assets/css/animate.min.css" rel="stylesheet"/>

  <!--  Light Bootstrap Table core CSS    -->
  <link href="../assets/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet"/>


  <!--  CSS for Demo Purpose, don't include it in your project     -->
  <link href="../assets/css/demo.css" rel="stylesheet" />


  <!--     Fonts and icons     -->
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
  <link href="../assets/css/pe-icon-7-stroke.css" rel="stylesheet" />
</head>
<body>

<div class="wrapper">
  <div class="sidebar" data-color="azure">

  <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->


    <div class="sidebar-wrapper">
          <div class="logo">
              <a href="#" class="simple-text">
                  APP NOTES
              </a>
          </div>

          <ul class="nav">
            <li>
                  <a href="http://localhost:3000/nota">
                      <i class="pe-7s-note2"></i>
                      <p>Notes</p>
                  </a>
              </li>
              <li>
                <%@user = current_user%>
                  <a href="http://localhost:3000/user/<%=@user.id%>">
                      <i class="pe-7s-user"></i>
                      <p>User Profile</p>

                  </a>
              </li>
              <li>
                  <a href="http://localhost:3000/categories">
                      <i class="pe-7s-news-paper"></i>
                      <p>Notes Collections</p>
                  </a>
              </li>
              <li>
                  <a href="http://localhost:3000/user">
                      <i class="pe-7s-science"></i>
                      <p>Search Users</p>
                  </a>
              </li>
              <li>
                  <a href="http://localhost:3000/user/<%=@user.id%>/following">
                      <i class="pe-7s-users"></i>
                      <p>Friends</p>
                  </a>
              </li>
              <li>
                  <a href="http://localhost:3000/user/<%=@user.id%>/followers">
                      <i class="pe-7s-bell"></i>
                      <p>Requests</p>
                  </a>
              </li>
          </ul>
    </div>
  </div>
  <div class="main-panel">
  <nav class="navbar navbar-default navbar-fixed">
          <div class="container-fluid">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                      <span class="sr-only">Toggle navigation</span>

                  </button>
                  <a class="navbar-brand" href="#">Notes</a>
              </div>
              <div class="collapse navbar-collapse">


                  <ul class="nav navbar-nav navbar-right">
                    <%if current_user.admin == true%>
                      <li>
                          <a href="http://localhost:3000/admin">
                                <p>Admin</p>
                            </a>
                        </li>
                      <%end%>

                      <li>
                              <li>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
              </li>
                      </li>
          <li class="separator hidden-lg hidden-md"></li>
                  </ul>
              </div>
          </div>
      </nav>

      <div class="content">
          <div class="container-fluid">
              <div class="row">
                  <div class="col-md-12">
                      <div class="card">
                          <div class="header">
                              <h4 class="title">Others Users</h4>
                          </div>
                          <div class="content table-responsive table-full-width">
                              <table class="table table-hover table-striped">
                                <thead>
                                  <tr>
                                    <th>Email</th>
                                    <th colspan="3"></th>
                                  </tr>
                                </thead>
                                <tbody>
                                  <% @users.each do |user| %>
                                  <%if user.email != current_user.email%>
                                    <tr>
                                      <td><%= user.email %></td>
                                      <td><%= link_to 'Show', user %></td>
                                    </tr>
                                  <%end%>
                                  <% end %>
                                </tbody>
                              </table>
                              <%= link_to 'Back', welcome_index_url %>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>

      <footer class="footer">
          <div class="container-fluid">
              <nav class="pull-left">
                  <ul>

                  </ul>
              </nav>
          </div>
      </footer>
  </div>
</div>

</body>

  <!--   Core JS Files   -->
  <script src="../assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>

<!--  Charts Plugin -->
<script src="../assets/js/chartist.min.js"></script>

  <!--  Notifications Plugin    -->
  <script src="../assets/js/bootstrap-notify.js"></script>

  <!--  Google Maps Plugin    -->
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

  <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
<script src="../assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
<script src="../assets/js/demo.js"></script>



</html>

app/views/user/show.html.erb
 <%if user_signed_in?%>
  <!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="icon" type="image/png" href="../assets/img/favicon.ico">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>Notes</title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="../assets/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="../assets/css/animate.min.css" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="../assets/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="../assets/css/demo.css" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="../assets/css/pe-icon-7-stroke.css" rel="stylesheet" />
</head>
<body>

<div class="wrapper">
    <div class="sidebar" data-color="azure">

    <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->


      <div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    APP NOTES
                </a>
            </div>

            <ul class="nav">
              <li >
                    <a href="http://localhost:3000/nota">
                        <i class="pe-7s-note2"></i>
                        <p>Notes</p>
                    </a>
                </li>
                <li>
                  <%@user = current_user%>
                    <a href="http://localhost:3000/user/<%=@user.id%>">
                        <i class="pe-7s-user"></i>
                        <p>User Profile</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/categories">
                        <i class="pe-7s-news-paper"></i>
                        <p>Notes Collections</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user">
                        <i class="pe-7s-science"></i>
                        <p>Search Users</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user/<%=@user.id%>/following">
                        <i class="pe-7s-users"></i>
                        <p>Friends</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user/<%=@user.id%>/followers">
                        <i class="pe-7s-bell"></i>
                        <p>Requests</p>
                    </a>
                </li>
            </ul>
      </div>
    </div>
    <div class="main-panel">
    <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>

                    </button>
                    <a class="navbar-brand" href="#">Notes</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                      <%if current_user.admin == true%>
                        <li>
                            <a href="http://localhost:3000/admin">
                                  <p>Admin</p>
                              </a>
                          </li>
                        <%end%>
                        <li>
                                <li>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
                </li>
                        </li>
            <li class="separator hidden-lg hidden-md"></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">Profile</h4>
                            </div>

                            <div class="panel panel-default">
                                <div class="panel-heading">
                                  <h3 class="panel-title"> User Email </h3>
                                </div>
                                <div class="panel-body">
                                    <%= @users.email %>
                                    <section class="stats">
                                      <%= render 'shared/stats' %>
                                    </section>
                                    <%if current_user.id != @users.id%>
                                      <%= render 'follow_form'%>
                                    <%end%>
                                </div>
                                <div class="panel-body">
                                <%if current_user.following?(@users) && @users.following?(current_user)%>
                                <br>
                                  <strong>Notes:</strong>
                                    <table class="table table-hover table-striped">
                                        <thead>
                                          <tr>
                                            <th>Title</th>
                                            <th>Body</th>
                                            <th colspan="3"></th>
                                          </tr>
                                        </thead>
                                        <tbody>
                                            <% @users.notum.each do |notum| %>
                                              <tr>
                                                <td><%= notum.title %></td>
                                                <td><%= notum.body %></td>
                                                <td><%= link_to 'Show', notum %></td>
                                              </tr>
                                            <% end %>
                                        </tbody>
                                    </table>
                                  <%end%>
                                  <%= link_to 'Back', user_index_url %>
                                </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>

                    </ul>
                </nav>
            </div>
        </footer>
    </div>
</div>

</body>

    <!--   Core JS Files   -->
    <script src="../assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
  <script src="../assets/js/bootstrap.min.js" type="text/javascript"></script>

  <!--  Charts Plugin -->
  <script src="../assets/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="../assets/js/bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
  <script src="../assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

  <!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
  <script src="../assets/js/demo.js"></script>



</html>

<%end%>

app/views/user/show_follow.html.erb
<%if user_signed_in?%>
  <!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="icon" type="image/png" href="../../assets/img/favicon.ico">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>Notes</title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="../../assets/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="../../assets/css/animate.min.css" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="../../assets/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="../../assets/css/demo.css" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="../../assets/css/pe-icon-7-stroke.css" rel="stylesheet" />
</head>
<body>

<div class="wrapper">
    <div class="sidebar" data-color="azure">

    <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->


      <div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    APP NOTES
                </a>
            </div>

            <ul class="nav">
              <li>
                    <a href="http://localhost:3000/nota">
                        <i class="pe-7s-note2"></i>
                        <p>Notes</p>
                    </a>
                </li>
                <li>
                  <%@user = current_user%>
                    <a href="http://localhost:3000/user/<%=@user.id%>">
                        <i class="pe-7s-user"></i>
                        <p>User Profile</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/categories">
                        <i class="pe-7s-news-paper"></i>
                        <p>Notes Collections</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user">
                        <i class="pe-7s-science"></i>
                        <p>Search Users</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user/<%=@user.id%>/following">
                        <i class="pe-7s-users"></i>
                        <p>Friends</p>
                    </a>
                </li>


                  <li>
                    <a href="http://localhost:3000/user/<%=@user.id%>/followers">

                        <i class="pe-7s-bell"></i>
                        <p>Requests</p>
                    </a>
                </li>
            </ul>
      </div>
    </div>
    <div class="main-panel">
    <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>

                    </button>
                    <a class="navbar-brand" href="#">Notes</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                      <%if current_user.admin == true%>
                        <li>
                            <a href="http://localhost:3000/admin">
                                  <p>Admin</p>
                              </a>
                          </li>
                        <%end%>
                        <li>
                                <li>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
                </li>
                        </li>
            <li class="separator hidden-lg hidden-md"></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h4 class="title"></h4>
                            </div>
                            <div class="content table-responsive table-full-width">
                                <table class="table table-hover table-striped">
                                  <div class="col-md-8">
                                  <% provide(:title, @title) %>
                                        <h4>Current User: <%= @user.email %></h4>
                                        <span>Notes: <%= @user.notum.count %></span>
                                      <section class="stats">
                                        <% if @users.any? %>
                                          <div class="user_avatars">
                                            <% @users.each do |user| %>
                                            <% end %>
                                          </div>
                                        <% end %>
                                      </section>

                                      <% if @title == "Friends"%>
                                      <h3><%= @title %></h3>
                                      <% if @users.any? %>
                                        <ul class="users follow">

                                            <% @users.each do |user| %>
                                                <%if current_user.following?(user)  && user.following?(current_user) %>
                                                <thead>
                                                  <tr>
                                                    <th>Name</th>
                                                    <th colspan="3"></th>
                                                  </tr>
                                                </thead>
                                                  <tbody>
                                                  <tr>
                                                    <td><%= user.email %></td>
                                                    <td><%= link_to 'Show',user %></td>
                                                    <td><%= link_to 'Destroy',user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                                  </tr>
                                               <% end %>
                                            <% end %>
                                          </tbody>
                                        </ul>
                                        <% end %>
                                      <%end%>

                                      <% if @title == "Requests"%>

                                      <h3><%= @title %></h3>
                                      <% if @users.any? %>
                                        <ul class="users follow">
                                                    <thead>
                                                      <tr>
                                                        <th>Name</th>
                                                        <th colspan="3"></th>
                                                      </tr>
                                                    </thead>
                                                    <tbody>

                                            <% @users.each do |user| %>
                                                <%if current_user.followers?(user) && current_user.following?(user) == false%>
                                                    <tr>
                                                    <td><%= user.email %></td>
                                                    <td><%= link_to 'Show',user %></td>
                                                    <td><%= link_to 'Destroy',user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                                    </tr>
                                               <% end %>
                                            <% end %>
                                                  </tbody>
                                        </ul>
                                        <% end %>
                                      <%end%>

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>

                    </ul>
                </nav>
            </div>
        </footer>
    </div>
</div>

</body>

    <!--   Core JS Files   -->
    <script src="../../assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
  <script src="../../assets/js/bootstrap.min.js" type="text/javascript"></script>

  <!--  Charts Plugin -->
  <script src="../../assets/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="../../assets/js/bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
  <script src="../../assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

  <!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
  <script src="../../assets/js/demo.js"></script>



</html>

<%end%>