config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :categories
  resources :user

  devise_for :users
  get 'welcome/index'

  resources :nota
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root 'welcome#index'
  #root  'sessions#new'

  devise_scope :user do
    authenticated :user do
      root 'welcome#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end



   resources :user do
    member do
      get :following, :followers
    end
  end

  resources :relationships,       only: [:create, :destroy]


end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :has_categories ,dependent:   :destroy
  has_many :notum, through: :has_categories
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
#before_action :set_categories
before_action :authenticate_user!


def create

  @categories = current_user.Category.new(category_params)


  respond_to do |format|
    if @categories.save
      format.html { redirect_to @categories, notice: 'Notum was successfully created.' }
      format.json { render :show, status: :created, location: @categories }
    else
      format.html { render :new }
      format.json { render json: @categories.errors, status: :unprocessable_entity }
    end
  end
end

 #private

   def category_params
     params.require(:category).permit(:name)
   end
#end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
 <%if user_signed_in?%>
  <!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="icon" type="image/png" href="../../assets/img/favicon.ico">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>Notes</title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="../../assets/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="../../assets/css/animate.min.css" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="../../assets/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="../../assets/css/demo.css" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="../../assets/css/pe-icon-7-stroke.css" rel="stylesheet" />
</head>
<body>

<div class="wrapper">
    <div class="sidebar" data-color="azure">

    <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->


      <div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    APP NOTES
                </a>
            </div>

            <ul class="nav">
              <li>
                    <a href="http://localhost:3000/nota">
                        <i class="pe-7s-note2"></i>
                        <p>Notes</p>
                    </a>
                </li>
                <li>
                  <%@user = current_user%>
                    <a href="http://localhost:3000/user/<%=@user.id%>">
                        <i class="pe-7s-user"></i>
                        <p>User Profile</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/categories">
                        <i class="pe-7s-news-paper"></i>
                        <p>Notes Collections</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user">
                        <i class="pe-7s-science"></i>
                        <p>Search Users</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user/<%=@user.id%>/following">
                        <i class="pe-7s-users"></i>
                        <p>Friends</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user/<%=@user.id%>/followers">
                        <i class="pe-7s-bell"></i>
                        <p>Requests</p>
                    </a>
                </li>
            </ul>
      </div>
    </div>
    <div class="main-panel">
    <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>

                    </button>
                    <a class="navbar-brand" href="#">Notes</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                      <%if current_user.admin == true%>
                        <li>
                            <a href="http://localhost:3000/admin">
                                  <p>Admin</p>
                              </a>
                          </li>
                        <%end%>
                        <li>
                                <li>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
                </li>
                        </li>
            <li class="separator hidden-lg hidden-md"></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">Collecction:</h4>
                            </div>
                            <div class="content table-responsive table-full-width">
                            	<h1>Editing Collecction</h1>
								<%= render 'form', category: @category %>
                                <table class="table table-hover table-striped">

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>

                    </ul>
                </nav>
            </div>
        </footer>
    </div>
</div>

</body>

    <!--   Core JS Files   -->
    <script src="../../assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
  <script src="../../assets/js/bootstrap.min.js" type="text/javascript"></script>

  <!--  Charts Plugin -->
  <script src="../../assets/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="../../assets/js/bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
  <script src="../../assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

  <!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
  <script src="../../assets/js/demo.js"></script>



</html>

<%end%>

app/views/categories/index.html.erb
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<link rel="icon" type="image/png" href="assets/img/favicon.ico">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

<title>Notes</title>

<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
  <meta name="viewport" content="width=device-width" />


  <!-- Bootstrap core CSS     -->
  <link href="assets/css/bootstrap.min.css" rel="stylesheet" />

  <!-- Animation library for notifications   -->
  <link href="assets/css/animate.min.css" rel="stylesheet"/>

  <!--  Light Bootstrap Table core CSS    -->
  <link href="assets/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet"/>


  <!--  CSS for Demo Purpose, don't include it in your project     -->
  <link href="assets/css/demo.css" rel="stylesheet" />


  <!--     Fonts and icons     -->
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
  <link href="assets/css/pe-icon-7-stroke.css" rel="stylesheet" />
</head>
<body>

<div class="wrapper">
  <div class="sidebar" data-color="azure">

  <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->


    <div class="sidebar-wrapper">
          <div class="logo">
              <a href="#" class="simple-text">
                  APP NOTES
              </a>
          </div>

          <ul class="nav">
            <li>
                  <a href="http://localhost:3000/nota">
                      <i class="pe-7s-note2"></i>
                      <p>Notes</p>
                  </a>
              </li>
              <li>
                <%@user = current_user%>
                  <a href="http://localhost:3000/user/<%=@user.id%>">
                      <i class="pe-7s-user"></i>
                      <p>User Profile</p>

                  </a>
              </li>
              <li>
                  <a href="http://localhost:3000/categories">
                      <i class="pe-7s-news-paper"></i>
                      <p>Notes Collections</p>
                  </a>
              </li>
              <li>
                  <a href="http://localhost:3000/user">
                      <i class="pe-7s-science"></i>
                      <p>Search Users</p>
                  </a>
              </li>
              <li>
                  <a href="http://localhost:3000/user/<%=@user.id%>/following">
                      <i class="pe-7s-users"></i>
                      <p>Friends</p>
                  </a>
              </li>
              <li>
                  <a href="http://localhost:3000/user/<%=@user.id%>/followers">
                      <i class="pe-7s-bell"></i>
                      <p>Requests</p>
                  </a>
              </li>
          </ul>
    </div>
  </div>
  <div class="main-panel">
  <nav class="navbar navbar-default navbar-fixed">
          <div class="container-fluid">
              <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                      <span class="sr-only">Toggle navigation</span>

                  </button>
                  <a class="navbar-brand" href="#">Notes</a>
              </div>
              <div class="collapse navbar-collapse">
                  <ul class="nav navbar-nav navbar-right">
                    <%if current_user.admin == true%>
                      <li>
                          <a href="http://localhost:3000/admin">
                                <p>Admin</p>
                            </a>
                        </li>
                      <%end%>

                      <li>
                              <li>
                <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
              </li>
                      </li>
          <li class="separator hidden-lg hidden-md"></li>
                  </ul>
              </div>
          </div>
      </nav>

      <div class="content">
          <div class="container-fluid">
              <div class="row">
                  <div class="col-md-12">
                      <div class="card">
                          <div class="header">
                              <h4 class="title">Collections</h4>
                          </div>
                          <div class="content table-responsive table-full-width">
                            <p id="notice"><%= notice %></p>
                              <table class="table table-hover table-striped">
                                  <%@categories = current_user.Category.all%>
                                    <thead>
                                      <tr>
                                        <th>Name</th>
                                        <th colspan="3"></th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                      <% @categories.each do |category| %>
                                        <tr>
                                          <td><%= category.name %></td>
                                          <td><%= link_to 'Show', category %></td>
                                          <td><%= link_to 'Edit', edit_category_path(category) %></td>
                                          <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                        </tr>
                                      <% end %>
                                    </tbody>
                              </table>
                              <%= link_to 'New Category', new_category_path %>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>

      <footer class="footer">
          <div class="container-fluid">
              <nav class="pull-left">
                  <ul>

                  </ul>
              </nav>
          </div>
      </footer>
  </div>
</div>

</body>

  <!--   Core JS Files   -->
  <script src="assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="assets/js/bootstrap.min.js" type="text/javascript"></script>

<!--  Charts Plugin -->
<script src="assets/js/chartist.min.js"></script>

  <!--  Notifications Plugin    -->
  <script src="assets/js/bootstrap-notify.js"></script>

  <!--  Google Maps Plugin    -->
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

  <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
<script src="assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
<script src="assets/js/demo.js"></script>



</html>

app/views/categories/new.html.erb
 <%if user_signed_in?%>
  <!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="icon" type="image/png" href="../../assets/img/favicon.ico">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>Notes</title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="../../assets/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="../../assets/css/animate.min.css" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="../../assets/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="../../assets/css/demo.css" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="../../assets/css/pe-icon-7-stroke.css" rel="stylesheet" />
</head>
<body>

<div class="wrapper">
    <div class="sidebar" data-color="azure">

    <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->


      <div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    APP NOTES
                </a>
            </div>

            <ul class="nav">
              <li>
                    <a href="http://localhost:3000/nota">
                        <i class="pe-7s-note2"></i>
                        <p>Notes</p>
                    </a>
                </li>
                <li>
                  <%@user = current_user%>
                    <a href="http://localhost:3000/user/<%=@user.id%>">
                        <i class="pe-7s-user"></i>
                        <p>User Profile</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/categories">
                        <i class="pe-7s-news-paper"></i>
                        <p>Notes Collections</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user">
                        <i class="pe-7s-science"></i>
                        <p>Search Users</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user/<%=@user.id%>/following">
                        <i class="pe-7s-users"></i>
                        <p>Friends</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user/<%=@user.id%>/followers">
                        <i class="pe-7s-bell"></i>
                        <p>Requests</p>
                    </a>
                </li>
            </ul>
      </div>
    </div>
    <div class="main-panel">
    <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>

                    </button>
                    <a class="navbar-brand" href="#">Notes</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                      <%if current_user.admin == true%>
                        <li>
                            <a href="http://localhost:3000/admin">
                                  <p>Admin</p>
                              </a>
                          </li>
                        <%end%>
                        <li>
                                <li>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
                </li>
                        </li>
            <li class="separator hidden-lg hidden-md"></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">New Collecction:</h4>
                            </div>
                            <div class="content table-responsive table-full-width">
                            	<%= render 'form', category: @category %>
								<%= link_to 'Back', categories_path %>
                                <table class="table table-hover table-striped">

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>

                    </ul>
                </nav>
            </div>
        </footer>
    </div>
</div>

</body>

    <!--   Core JS Files   -->
    <script src="../../assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
  <script src="../../assets/js/bootstrap.min.js" type="text/javascript"></script>

  <!--  Charts Plugin -->
  <script src="../../assets/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="../../assets/js/bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
  <script src="../../assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

  <!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
  <script src="../../assets/js/demo.js"></script>



</html>

<%end%>

app/views/categories/show.html.erb
 <%if user_signed_in?%>
  <!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <link rel="icon" type="image/png" href="../../assets/img/favicon.ico">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>Notes</title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="../../assets/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="../../assets/css/animate.min.css" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="../../assets/css/light-bootstrap-dashboard.css?v=1.4.0" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="../../assets/css/demo.css" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="../../assets/css/pe-icon-7-stroke.css" rel="stylesheet" />
</head>
<body>

<div class="wrapper">
    <div class="sidebar" data-color="azure">

    <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->


      <div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    APP NOTES
                </a>
            </div>

            <ul class="nav">
              <li>
                    <a href="http://localhost:3000/nota">
                        <i class="pe-7s-note2"></i>
                        <p>Notes</p>
                    </a>
                </li>
                <li>
                  <%@user = current_user%>
                    <a href="http://localhost:3000/user/<%=@user.id%>">
                        <i class="pe-7s-user"></i>
                        <p>User Profile</p>
                    </a>
                </li>
                <li>

                    <a href="http://localhost:3000/categories">
                        <i class="pe-7s-news-paper"></i>
                        <p>Notes Collections</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user">
                        <i class="pe-7s-science"></i>
                        <p>Search Users</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user/<%=@user.id%>/following">
                        <i class="pe-7s-users"></i>
                        <p>Friends</p>
                    </a>
                </li>
                <li>
                    <a href="http://localhost:3000/user/<%=@user.id%>/followers">
                        <i class="pe-7s-bell"></i>
                        <p>Requests</p>
                    </a>
                </li>
            </ul>
      </div>
    </div>
    <div class="main-panel">
    <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                    </button>
                    <a class="navbar-brand" href="#">Notes</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                      <%if current_user.admin == true%>
                        <li>
                            <a href="http://localhost:3000/admin">
                                  <p>Admin</p>
                              </a>
                          </li>
                        <%end%>
                        <li>
                                <li>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
                </li>
                        </li>
            <li class="separator hidden-lg hidden-md"></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h3 class="title">Collection: <%= @category.name %></h3>
                            </div>
                            <div class="content table-responsive table-full-width">
                                <table class="table table-hover table-striped">
              									<h4>Notes in this Collections:</h4>
              									      <thead>
                                            <tr>
                                              <th>Title</th>
                                              <th>Body</th>
                                              <th colspan="3"></th>
                                            </tr>
                                          </thead>
                                    <tbody>
									                 <% @category.notum.each do |notum| %>
									                    <tr>
                    									   <td> <%= link_to notum.title,notum %> </td>
                    									   <td><%=notum.body%></td>
                    									   <td><%=link_to "Delete Note",notum, method: :delete%></td>
                    									</tr>
                    									<%end%>
                                    </tbody>
                                </table>
								<%= link_to 'Edit', edit_category_path(@category) %> |
								<%= link_to 'Back', categories_path %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>

                    </ul>
                </nav>
            </div>
        </footer>
    </div>
</div>

</body>

    <!--   Core JS Files   -->
    <script src="../../assets/js/jquery.3.2.1.min.js" type="text/javascript"></script>
  <script src="../../assets/js/bootstrap.min.js" type="text/javascript"></script>

  <!--  Charts Plugin -->
  <script src="../../assets/js/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="../../assets/js/bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
  <script src="../../assets/js/light-bootstrap-dashboard.js?v=1.4.0"></script>

  <!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
  <script src="../../assets/js/demo.js"></script>



</html>

<%end%>